Repository CapstoneLabs/slick, pull requests merged in 2018-10, with the labels that each got.

#9 Add Go Module support
  bot.go
  deployer/deployer.go
  go.mod
  go.sum
Labels: enhancement

#11 Add channel tests
  .gitignore
  Makefile
  channel.go
  channel_test.go
  go.mod
  go.sum
Labels: enhancement

#15 #6 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#19 #18 Refactor to use testify package
  channel_test.go
  go.mod
  go.sum
Labels: enhancement

#21 #20 Add message.go tests
  go.mod
  go.sum
  listener_test.go
  message.go
  message_test.go
Labels: enhancement

#25 fix failing test, make them pass
  faceoff/faceoff_test.go
  standup/standupDate.go
  standup/standupDate_test.go
Labels: bug

#33 Add CI tests
  .travis.yml
  Makefile
  scripts/pre-commit.sh
Labels: enhancement

#35 #34 Fix asana test formatting
  asana/asana_test.go
Labels: bug

#36 Update readme and housekeeping
  .ackrc
  README.md
  example-bot/slick.sample.conf
Labels: enhancement

#38 Updated message_test.go to testify's recommended format.
  message_test.go
Labels: bug

#41 #40 remove Plotly plugins
  example-bot/main.go
  legacy-plugins/blaster/blaster.go
  legacy-plugins/blaster/blaster_test.go
  legacy-plugins/blaster/tries.go
  legacy-plugins/deployer/deployer.go
  legacy-plugins/deployer/deployer_web.go
  legacy-plugins/deployer/params.go
  legacy-plugins/totw/totw.go
Labels: enhancement

#43 #42 Add package level docs
  .gitignore
  asana/asana.go
  bot.go
  github/github.go
  healthy/healthy.go
  plotberry/plotberry.go
  recognition/recognize.go
  standup/standup.go
  todo/todo.go
  vote/vote.go
  wicked/wicked.go
Labels: Hacktoberfest, enhancement

#44 Test for dates
  dates.go
  dates_test.go
  legacy-plugins/totw/totw.go
  mooder/mooder.go
Labels: Hacktoberfest, enhancement

#49 #48 Add Issue/PR templates and update CONTRIBUTING
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/generic.md
  CODEOWNERS
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: enhancement

#51 Update URL
  CODE_OF_CONDUCT.md
  docs-src/config.yaml
  docs/404.html
  docs/categories/index.html
  docs/categories/index.xml
  docs/code-of-conduct/index.html
  docs/code-of-conduct/index.xml
  docs/index.html
  docs/index.json
  docs/index.xml
  docs/plugins/index.html
  docs/plugins/index.xml
  docs/press-kit/index.html
  docs/press-kit/index.xml
  docs/sitemap.xml
  docs/tags/index.html
  docs/tags/index.xml
Labels: bug

#54 #37 Add CI Releases
  .travis.yml
  VERSION
Labels: enhancement
